### ISSUE TITLE
请问能用于生产的版本什么时候release?

### ISSUE THREAD

**Issue by supercocoa7654** [alibaba/havenask-federation#160]
很棒的项目，看了下比直接裸用havenask方便多了，大概什么时候能realse一个稳定版可以用于生产环境的？

**Comment by weizijun** [comment]
> 很棒的项目，看了下比直接裸用havenask方便多了，大概什么时候能realse一个稳定版可以用于生产环境的？

这是一个全新的项目，我们计划在8月底的时候release一个单机版本。不过这个版本由于没有分布式和高可用，仅仅作为使用体验和测试。接下来我们会开始分布式版本的研发，计划是在年底前release一个生产环境可用的稳定版本。
