### ISSUE TITLE
删除索引后马上创建索引可能会遇到searcher启动超时，此时写入会报错

### ISSUE THREAD

**Issue by Jixin10** [alibaba/havenask-federation#194]
![image](https://github.com/alibaba/havenask-federation/assets/50186999/d43bdc15-fd0f-4ad0-a4bc-e5584da8f440)
![image](https://github.com/alibaba/havenask-federation/assets/50186999/dac87fb8-a87d-4ddc-91c7-aa326ce19a9f)

**Comment by weizijun** [comment]
重构的元数据同步方式已解决该问题
