### ISSUE TITLE
searcher手动停掉后无法启动，有端口占用情况

### ISSUE THREAD

**Issue by Jixin10** [alibaba/havenask-federation#200]
具体触发方式：创建索引后写入几条文档，然后手动kill掉searcher进程，之后触发searcher重启触发recovery时，searcher一直重启不成功。查看ha3的log，发现arpc的端口39200被general_search_updater占用。

**Comment by weizijun** [comment]
fixed by https://github.com/alibaba/havenask-federation/pull/203
