### ISSUE TITLE
org.havenask.engine.search.SearchIT报错，需适配最新元数据同步机制

### ISSUE THREAD

**Issue by weizijun** [alibaba/havenask-federation#256]
报错case：
```
./gradlew ':modules:havenask-engine:internalClusterTest' --tests "org.havenask.engine.search.SearchIT"
```

**Comment by Huaixinww** [comment]
报错原因为SearchIT测试时会将enabled设置为false，导致MetaDataSyncer无法执行SyncTask进行同步
metaDataSyncer.getSearcherTargetInfo值为null导致checkTableStatus()不通过。
![image](https://github.com/alibaba/havenask-federation/assets/141887897/816b53c8-ff90-4bc4-a124-5797638c47fb)

**Comment by Huaixinww** [comment]
fixed by:https://github.com/alibaba/havenask-federation/pull/490
