### ISSUE TITLE
删除索引后马上创建同名新索引，可能会直接显示green，但是实际上同步未完成

### ISSUE THREAD

**Issue by Huaixinww** [alibaba/havenask-federation#263]
节点状态显示green，但是此时尝试写入数据会报错
![image](https://github.com/alibaba/havenask-federation/assets/141887897/c4f6894d-b6a9-498f-a929-219c2873f927)

**Comment by weizijun** [comment]
fix by: https://github.com/alibaba/havenask-federation/pull/268
