### ISSUE TITLE
支持导入es索引

### ISSUE THREAD

**Issue by zwx2403** [alibaba/havenask-federation#31]
1.支持导入es 的mapping和setting
2.支持导入es 索引数据

**Comment by weizijun** [comment]
目前计划通过reindex支持将es索引导入成havenask索引。
reindex可以通过配置远程集群，将远程es集群的索引导入成本地havenask索引。
后面相关开发内容会在此issue上记录

**Comment by weizijun** [comment]
支持写入的特性：https://github.com/alibaba/havenask-federation/pull/64 合并后，可以支持通过index、delete、bulk接口将数据写入havenask。同时也支持了reindex接口。
reindex功能使用，可参见wiki：[通过reindex功能，将ES数据导入Havenask](https://github.com/alibaba/havenask-federation/wiki/%E9%80%9A%E8%BF%87reindex%E5%8A%9F%E8%83%BD%EF%BC%8C%E5%B0%86ES%E6%95%B0%E6%8D%AE%E5%AF%BC%E5%85%A5Havenask)
