### ISSUE TITLE
对于entry_table的解析可能存在bad case

### ISSUE THREAD

**Issue by Huaixinww** [alibaba/havenask-federation#320]
目前对entry_table的解析，key只考虑了当前fence目录以及跟目录两种情况。
即：
"":当前fence目录的文件
后缀为"partition_0_65535":根目录；

但是如果存在searcher被kill掉又被拉起的情况，可能会出现多个fence目录
此时的entry_table的key可能会有后缀为fence目录的情况
即key为  "\/usr\/share\/havenask\/data\/havenask\/local_search_12000\/general_p0_r0\/runtimedata\/test1\/generation_0\/partition_0_65535\/__FENCE__eXmV5TSeo69lhs5Pbq3C"

**Comment by weizijun** [comment]
fixed by https://github.com/alibaba/havenask-federation/pull/427
