### ISSUE TITLE
peer recovery后会遗留空目录问题

### ISSUE THREAD

**Issue by Huaixinww** [alibaba/havenask-federation#322]
peerRecovery时，由于rename阶段只rename了文件，因此会遗留带recovery.前缀的目录以及其子目录
![image](https://github.com/alibaba/havenask-federation/assets/141887897/fba89bf9-9e5c-44b3-a39b-d10a110939dc)

**Comment by weizijun** [comment]
fixed by https://github.com/alibaba/havenask-federation/pull/323
