### ISSUE TITLE
创建字段名称包含中划线时，sql会报错，导致search接口无法查询数据

### ISSUE THREAD

**Issue by Huaixinww** [alibaba/havenask-federation#381]
示例如下：
```
PUT test_index
{
  "settings": {
    "index.engine": "havenask",
    "number_of_shards": 3, 
    "number_of_replicas": 0
  },
  "mappings": {
    "properties": {
      "foo-test": {
        "type": "keyword"
      }
    }
  }
}
```
使用`GET _havenask/sql?query=select * from test-index`进行查询
报错信息如下:
Create outputName [foo-test] expr [foo-test] failed.
![image](https://github.com/alibaba/havenask-federation/assets/141887897/0061ce21-8ddb-42dd-888e-212832f6338b)

**Comment by weizijun** [comment]
havenask字段不支持中划线，在HavenaskIndexMappingProvider.validateIndexMapping判断下字段名称，包含中划线的字段需要再创建时报错

**Comment by weizijun** [comment]
fixed by https://github.com/alibaba/havenask-federation/pull/401
